// Cubik Template version 1.0
// Java generated by Cubik 0.96
// Be sure to check the code and adapt it to your need
// BDcraft.net

package sirttas.alchemytech.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ShakerBarrelModel extends ModelBase {

	public ModelRenderer barrel;

	FloatModelRenderer Elem48;// Element
	FloatModelRenderer Elem47;// Element
	FloatModelRenderer Elem42;// Element
	FloatModelRenderer Elem41;// Element
	ModelRenderer Elem40;// Element
	FloatModelRenderer Elem39;// Element
	FloatModelRenderer Elem38;// Element
	FloatModelRenderer Elem37;// Element
	ModelRenderer Elem36;// Element
	FloatModelRenderer Elem35;// Element
	FloatModelRenderer Elem34;// Element
	FloatModelRenderer Elem33;// Element
	FloatModelRenderer Elem32;// Element
	FloatModelRenderer Elem31;// Element
	FloatModelRenderer Elem30;// Element
	FloatModelRenderer Elem29;// Element
	FloatModelRenderer Elem28;// Element
	FloatModelRenderer Elem27;// Element
	FloatModelRenderer Elem26;// Element
	FloatModelRenderer Elem25;// Element
	FloatModelRenderer Elem24;// Element

	public ShakerBarrelModel() {
		textureWidth = 64;
		textureHeight = 32;

		barrel = new ModelRenderer(this, 0, 0);
		barrel.setRotationPoint(0F, 0F, 0F);
		barrel.offsetY = 3.5F / 16F;
		barrel.setTextureSize(64, 32);
		setRotation(barrel, -0F, -0F, -0F);

		// Element
		Elem48 = new FloatModelRenderer(this, 0, 0);
		Elem48.addBox(-3F, -0.5F, -0.5F, 1.5F, 1, 1);
		Elem48.setTextureSize(64, 32);
		setRotation(Elem48, -0F, -0F, -0F);
		// Elem48.rotateAngleX = -0F;
		// Elem48.rotateAngleY = -0F;
		// Elem48.rotateAngleZ = -0F;
		Elem48.mirror = false;
		barrel.addChild(Elem48);
		// Element
		Elem47 = new FloatModelRenderer(this, 0, 0);
		Elem47.addBox(1.5F, -0.5F, -0.5F, 1.5F, 1, 1);
		Elem47.setTextureSize(64, 32);
		setRotation(Elem47, -0F, -0F, -0F);
		// Elem47.rotateAngleX = -0F;
		// Elem47.rotateAngleY = -0F;
		// Elem47.rotateAngleZ = -0F;
		Elem47.mirror = false;
		barrel.addChild(Elem47);
		// Element
		Elem42 = new FloatModelRenderer(this, 0, 0);
		Elem42.addBox(-1.5F, -2.5F, -1.5F, 0.5F, 6, 3);
		Elem42.setTextureSize(64, 32);
		setRotation(Elem42, -0F, -0F, -0F);
		// Elem42.rotateAngleX = -0F;
		// Elem42.rotateAngleY = -0F;
		// Elem42.rotateAngleZ = -0F;
		Elem42.mirror = false;
		barrel.addChild(Elem42);
		// Element
		Elem41 = new FloatModelRenderer(this, 0, 0);
		Elem41.addBox(1F, -2.5F, -1.5F, 0.5F, 6, 3);
		Elem41.setTextureSize(64, 32);
		setRotation(Elem41, -0F, -0F, -0F);
		// Elem41.rotateAngleX = -0F;
		// Elem41.rotateAngleY = -0F;
		// Elem41.rotateAngleZ = -0F;
		Elem41.mirror = false;
		barrel.addChild(Elem41);
		// Element
		Elem40 = new ModelRenderer(this, 0, 0);
		Elem40.addBox(-1.5F, 1F, -1.5F, 3, 2, 3);
		Elem40.setTextureSize(64, 32);
		setRotation(Elem40, -0F, -0F, -0F);
		// Elem40.rotateAngleX = -0F;
		// Elem40.rotateAngleY = -0F;
		// Elem40.rotateAngleZ = -0F;
		Elem40.mirror = false;
		barrel.addChild(Elem40);
		// Element
		Elem39 = new FloatModelRenderer(this, 0, 0);
		Elem39.addBox(1F, -1F, -2F, 0.5F, 2, 0.5F);
		Elem39.setTextureSize(64, 32);
		setRotation(Elem39, -0F, -0F, -0F);
		// Elem39.rotateAngleX = -0F;
		// Elem39.rotateAngleY = -0F;
		// Elem39.rotateAngleZ = -0F;
		Elem39.mirror = false;
		barrel.addChild(Elem39);
		// Element
		Elem38 = new FloatModelRenderer(this, 0, 0);
		Elem38.addBox(-1.5F, -1F, -2F, 0.5F, 2, 0.5F);
		Elem38.setTextureSize(64, 32);
		setRotation(Elem38, -0F, -0F, -0F);
		// Elem38.rotateAngleX = -0F;
		// Elem38.rotateAngleY = -0F;
		// Elem38.rotateAngleZ = -0F;
		Elem38.mirror = false;
		barrel.addChild(Elem38);
		// Element
		Elem37 = new FloatModelRenderer(this, 0, 0);
		Elem37.addBox(-1.5F, 1F, -2F, 3, 2, 0.5F);
		Elem37.setTextureSize(64, 32);
		setRotation(Elem37, -0F, -0F, -0F);
		// Elem37.rotateAngleX = -0F;
		// Elem37.rotateAngleY = -0F;
		// Elem37.rotateAngleZ = -0F;
		Elem37.mirror = false;
		barrel.addChild(Elem37);
		// Element
		Elem36 = new ModelRenderer(this, 0, 0);
		Elem36.addBox(-1.5F, -3.5F, -1.5F, 3, 1, 3);
		Elem36.setTextureSize(64, 32);
		setRotation(Elem36, -0F, -0F, -0F);
		// Elem36.rotateAngleX = -0F;
		// Elem36.rotateAngleY = -0F;
		// Elem36.rotateAngleZ = -0F;
		Elem36.mirror = false;
		barrel.addChild(Elem36);
		// Element
		Elem35 = new FloatModelRenderer(this, 0, 0);
		Elem35.addBox(-1.5F, 3F, -1.5F, 3, 0.5F, 3);
		Elem35.setTextureSize(64, 32);
		setRotation(Elem35, -0F, -0F, -0F);
		// Elem35.rotateAngleX = -0F;
		// Elem35.rotateAngleY = -0F;
		// Elem35.rotateAngleZ = -0F;
		Elem35.mirror = false;
		barrel.addChild(Elem35);
		// Element
		Elem34 = new FloatModelRenderer(this, 0, 0);
		Elem34.addBox(-2F, -0.5F, 0.5F, 0.5F, 1, 1);
		Elem34.setTextureSize(64, 32);
		setRotation(Elem34, -0F, -0F, -0F);
		// Elem34.rotateAngleX = -0F;
		// Elem34.rotateAngleY = -0F;
		// Elem34.rotateAngleZ = -0F;
		Elem34.mirror = false;
		barrel.addChild(Elem34);
		// Element
		Elem33 = new FloatModelRenderer(this, 0, 0);
		Elem33.addBox(-2F, -0.5F, -1.5F, 0.5F, 1, 1);
		Elem33.setTextureSize(64, 32);
		setRotation(Elem33, -0F, -0F, -0F);
		// Elem33.rotateAngleX = -0F;
		// Elem33.rotateAngleY = -0F;
		// Elem33.rotateAngleZ = -0F;
		Elem33.mirror = false;
		barrel.addChild(Elem33);
		// Element
		Elem32 = new FloatModelRenderer(this, 0, 0);
		Elem32.addBox(-2F, 0.5F, -1F, 0.5F, 2.5F, 2);
		Elem32.setTextureSize(64, 32);
		setRotation(Elem32, -0F, -0F, -0F);
		// Elem32.rotateAngleX = -0F;
		// Elem32.rotateAngleY = -0F;
		// Elem32.rotateAngleZ = -0F;
		Elem32.mirror = false;
		barrel.addChild(Elem32);
		// Element
		Elem31 = new FloatModelRenderer(this, 0, 0);
		Elem31.addBox(-1.5F, -3F, -2F, 3, 2, 0.5F);
		Elem31.setTextureSize(64, 32);
		setRotation(Elem31, -0F, -0F, -0F);
		// Elem31.rotateAngleX = -0F;
		// Elem31.rotateAngleY = -0F;
		// Elem31.rotateAngleZ = -0F;
		Elem31.mirror = false;
		barrel.addChild(Elem31);
		// Element
		Elem30 = new FloatModelRenderer(this, 0, 0);
		Elem30.addBox(1.5F, -0.5F, -1.5F, 0.5F, 1, 1);
		Elem30.setTextureSize(64, 32);
		setRotation(Elem30, -0F, -0F, -0F);
		// Elem30.rotateAngleX = -0F;
		// Elem30.rotateAngleY = -0F;
		// Elem30.rotateAngleZ = -0F;
		Elem30.mirror = false;
		barrel.addChild(Elem30);
		// Element
		Elem29 = new FloatModelRenderer(this, 0, 0);
		Elem29.addBox(1.5F, -0.5F, 0.5F, 0.5F, 1, 1);
		Elem29.setTextureSize(64, 32);
		setRotation(Elem29, -0F, -0F, -0F);
		// Elem29.rotateAngleX = -0F;
		// Elem29.rotateAngleY = -0F;
		// Elem29.rotateAngleZ = -0F;
		Elem29.mirror = false;
		barrel.addChild(Elem29);
		// Element
		Elem28 = new FloatModelRenderer(this, 0, 0);
		Elem28.addBox(1.5F, 0.5F, -1F, 0.5F, 2.5F, 2);
		Elem28.setTextureSize(64, 32);
		setRotation(Elem28, -0F, -0F, -0F);
		// Elem28.rotateAngleX = -0F;
		// Elem28.rotateAngleY = -0F;
		// Elem28.rotateAngleZ = -0F;
		Elem28.mirror = false;
		barrel.addChild(Elem28);
		// Element
		Elem27 = new FloatModelRenderer(this, 0, 0);
		Elem27.addBox(1.5F, -3F, -1F, 0.5F, 2.5F, 2);
		Elem27.setTextureSize(64, 32);
		setRotation(Elem27, -0F, -0F, -0F);
		// Elem27.rotateAngleX = -0F;
		// Elem27.rotateAngleY = -0F;
		// Elem27.rotateAngleZ = -0F;
		Elem27.mirror = false;
		barrel.addChild(Elem27);
		// Element
		Elem26 = new FloatModelRenderer(this, 0, 0);
		Elem26.addBox(-2F, -3F, -1F, 0.5F, 2.5F, 2);
		Elem26.setTextureSize(64, 32);
		setRotation(Elem26, -0F, -0F, -0F);
		// Elem26.rotateAngleX = -0F;
		// Elem26.rotateAngleY = -0F;
		// Elem26.rotateAngleZ = -0F;
		Elem26.mirror = false;
		barrel.addChild(Elem26);
		// Element
		Elem25 = new FloatModelRenderer(this, 0, 0);
		Elem25.addBox(-1.5F, -3F, 1.5F, 3, 6, 0.5F);
		Elem25.setTextureSize(64, 32);
		setRotation(Elem25, -0F, -0F, -0F);
		// Elem25.rotateAngleX = -0F;
		// Elem25.rotateAngleY = -0F;
		// Elem25.rotateAngleZ = -0F;
		Elem25.mirror = false;
		barrel.addChild(Elem25);
		// Element
		Elem24 = new FloatModelRenderer(this, 0, 0);
		Elem24.addBox(-1.5F, -3F, -1.5F, 3, 1.5F, 3);
		Elem24.setTextureSize(64, 32);
		setRotation(Elem24, -0F, -0F, -0F);
		// Elem24.rotateAngleX = -0F;
		// Elem24.rotateAngleY = -0F;
		// Elem24.rotateAngleZ = -0F;
		Elem24.mirror = false;
		barrel.addChild(Elem24);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		barrel.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity enity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, enity);
	}

}